### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by nobobo1234** [berzi/uniQword#2] opened 2018-02-13 19:10 UTC
So I was trying out your CLI with a huge study book of 1.2k pages (Thomas Calculus 13th edition).
I first did ``python uniqword.py`` and then did ``add_file Thomas_Calculus.pdf``. And after 3 minutes of running it showed that the list index was out of range 🤔 

```
Welcome. I am uniQword, I can count all the words in your files and more.
To begin, select a file with the "add_file" or "add_dir" command or type ? to re                                                                                                    ad a list of commands.
uniQword, add_file Thomas Calculus.pdf
I couldn't decode the file. Please save it in UTF-8 before retrying.
uniQword, add_file Thomas_Calculus.pdf
Traceback (most recent call last):
  File "uniqword.py", line 829, in <module>
    CommandLineInterface().cmdloop()
  File "c:\users\gebruiker\appdata\local\programs\python\python36\Lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "c:\users\gebruiker\appdata\local\programs\python\python36\Lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "uniqword.py", line 553, in do_add_file
    self.file.add_files(WordsFile(file, password))
  File "uniqword.py", line 52, in __init__
    self.store_all_words()
  File "uniqword.py", line 153, in store_all_words
    if word[0] == "-":
IndexError: list index out of range
```

Here's the error

**Comment by berzi** [comment] 2018-02-13 20:28
I attempted a fix (but haven't tested it).
The bug was probably caused by the program finding an empty word and trying to strip characters from it.

**Comment by nobobo1234** [comment] 2018-02-13 20:29
I'll try it out

**Comment by nobobo1234** [comment] 2018-02-13 20:42
@berzi Now it shows this 
```
uniQword, add_file Thomas_Calculus.pdf
Traceback (most recent call last):
  File "uniqword.py", line 812, in <module>
    CommandLineInterface().cmdloop()
  File "c:\users\gebruiker\appdata\local\programs\python\python36\Lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "c:\users\gebruiker\appdata\local\programs\python\python36\Lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "uniqword.py", line 536, in do_add_file
    self.file.add_files(WordsFile(file, password))
  File "uniqword.py", line 52, in __init__
    self.store_all_words()
  File "uniqword.py", line 138, in store_all_words
    if word[-1] == "-":
IndexError: list index out of range
``` 
I assume it's the same error, maybe it's because there is latex in there 🤔 
(edit: I just saw your "more bug fixing" commit, gonna try it again)

**Comment by nobobo1234** [comment] 2018-02-13 20:48
Nope, still happening

**Comment by berzi** [comment] 2018-02-13 22:16
Ouch. Well, I'll look into it tomorrow and try figuring out a fix. I haven't tested a wide variety of cases for PDFs yet, unfortunately.

**Comment by berzi** [comment] 2018-02-14 10:08
I think I identified the problem. I attempted a fix, please check if it's fixed on your end.

**Comment by nobobo1234** [comment] 2018-02-14 18:14
It works now ❤️

**Closed as completed** 2018-02-14 18:14 UTC
Labels: bug
